module.exports = {
  'acorn hall':
  {
    name: 'acorn hall',
    coords: { x: 735, y: 994 },
    region: 'The Riverlands',
  },
  ashemark: {
    name: 'ashemark',
    coords: { x: 494, y: 1005 },
    region: 'Westerlands',
  },
  'ashford castle': {
    name: 'ashford castle',
    coords: { x: 744, y: 465 },
    region: 'The Reach',
  },
  'baelish castle': {
    name: 'baelish castle',
    coords: { x: 1136, y: 1405 },
    region: 'The Vale',
  },
  bandallon: {
    name: 'bandallon',
    coords: { x: 308, y: 384 },
    region: 'The Reach',
  },
  'barrow hall': {
    name: 'barrow hall',
    coords: { x: 611, y: 1642 },
    region: 'The North',
  },
  'bear island': {
    name: 'bear island',
    coords: { x: 578, y: 2151 },
    region: 'The North',
  },
  bitterbridge: {
    name: 'bitterbridge',
    coords: { x: 746, y: 610 },
    region: 'The Reach',
  },
  blackcrown: {
    name: 'blackcrown',
    coords: { x: 290, y: 233 },
    region: 'The Reach',
  },
  blackmont: {
    name: 'blackmont',
    coords: { x: 600, y: 262 },
    region: 'Dorne',
  },
  'bloody gate': {
    name: 'bloody gate',
    coords: { x: 1044, y: 1029 },
    region: 'The Vale',
  },
  bluespine: {
    name: 'bluespine',
    coords: { x: 873, y: 853 },
    region: 'The Riverlands',
  },
  'brightwater keep': { name: 'brightwater keep', coords: { x: 385, y: 363 } },
  bronzehearth: { name: 'bronzehearth', coords: { x: 403, y: 1623 } },
  brownhollow: { name: 'brownhollow', coords: { x: 1245, y: 909 } },
  'casterly rock': { name: 'casterly rock', coords: { x: 367, y: 864 } },
  'castle cerwyn': { name: 'castle cerwyn', coords: { x: 766, y: 1861 } },
  'castle darry': { name: 'castle darry', coords: { x: 896, y: 1112 } },
  'cider hall': { name: 'cider hall', coords: { x: 642, y: 505 } },
  'cleganes keep': { name: 'cleganes keep', coords: { x: 366, y: 777 } },
  coldmoat: { name: 'coldmoat', coords: { x: 612, y: 640 } },
  'coldwater burn': { name: 'coldwater burn', coords: { x: 1176, y: 1354 } },
  crakehall: { name: 'crakehall', coords: { x: 312, y: 714 } },
  'deep den': { name: 'deep den', coords: { x: 541, y: 858 } },
  'deepwood motte': { name: 'deepwood motte', coords: { x: 580, y: 2000 } },
  dragonstone: { name: 'dragonstone', coords: { x: 1247, y: 876 } },
  driftmark: { name: 'driftmark', coords: { x: 1202, y: 857 } },
  'dun fort': { name: 'dun fort', coords: { x: 1106, y: 853 } },
  'dyre den': { name: 'dyre den', coords: { x: 1192, y: 940 } },
  erenford: { name: 'erenford', coords: { x: 762, y: 1180 } },
  faircastle: { name: 'faircastle', coords: { x: 356, y: 968 } },
  feastfires: { name: 'feastfires', coords: { x: 283, y: 853 } },
  'flints finger': { name: 'flints finger', coords: { x: 436, y: 1495 } },
  'gates of the moon': { name: 'gates of the moon', coords: { x: 1105, y: 1055 } },
  'ghost hill': { name: 'ghost hill', coords: { x: 1214, y: 150 } },
  godsgrace: { name: 'godsgrace', coords: { x: 1075, y: 122 } },
  'golden tooth': { name: 'golden tooth', coords: { x: 521, y: 926 } },
  goldengrove: { name: 'goldengrove', coords: { x: 537, y: 616 } },
  goldgrass: { name: 'goldgrass', coords: { x: 618, y: 1684 } },
  'grassfield keep': { name: 'grassfield keep', coords: { x: 831, y: 575 } },
  'grassy vale': { name: 'grassy vale', coords: { x: 884, y: 576 } },
  'greywater watch': { name: 'greywater watch', coords: { x: 803, y: 1457 } },
  harrenhal: { name: 'harrenhal', coords: { x: 891, y: 965 } },
  'hearts home': { name: 'hearts home', coords: { x: 1117, y: 1236 } },
  hellholt: { name: 'hellholt', coords: { x: 770, y: 129 } },
  'high hermitage': { name: 'high hermitage', coords: { x: 582, y: 204 } },
  highgarden: { name: 'highgarden', coords: { x: 529, y: 446 } },
  highpoint: { name: 'highpoint', coords: { x: 797, y: 2054 } },
  honeyhold: { name: 'honeyhold', coords: { x: 390, y: 316 } },
  'horn hill': { name: 'horn hill', coords: { x: 447, y: 386 } },
  hornvale: { name: 'hornvale', coords: { x: 579, y: 897 } },
  hornwood: { name: 'hornwood', coords: { x: 1053, y: 1788 } },
  ironoaks: { name: 'ironoaks', coords: { x: 1238, y: 1131 } },
  ironwrath: { name: 'ironwrath', coords: { x: 733, y: 2006 } },
  karhold: { name: 'karhold', coords: { x: 1269, y: 2021 } },
  kayce: { name: 'kayce', coords: { x: 308, y: 907 } },
  'kings landing': { name: 'kings landing', coords: { x: 1051, y: 744 } },
  kingsgrave: { name: 'kingsgrave', coords: { x: 743, y: 268 } },
  'last hearth': { name: 'last hearth', coords: { x: 1087, y: 2080 } },
  lemonwood: { name: 'lemonwood', coords: { x: 1203, y: 62 } },
  'long table': { name: 'long table', coords: { x: 697, y: 551 } },
  'longbow hall': { name: 'longbow hall', coords: { x: 1239, y: 1237 } },
  'moat cailin': { name: 'moat cailin', coords: { x: 819, y: 1560 } },
  'old anchor': { name: 'old anchor', coords: { x: 1266, y: 1158 } },
  'old oak': { name: 'old oak', coords: { x: 342, y: 583 } },
  oldcastle: { name: 'oldcastle', coords: { x: 982, y: 1507 } },
  oldtown: { name: 'oldtown', coords: { x: 362, y: 280 } },
  pinkmaiden: { name: 'pinkmaiden', coords: { x: 669, y: 960 } },
  'raventree hall': { name: 'raventree hall', coords: { x: 719, y: 1114 } },
  ramsgate: { name: 'ramsgate', coords: { x: 1141, y: 1654 } },
  'red Lake': { name: 'red Lake', coords: { x: 436, y: 654 } },
  'rillwater crossing': { name: 'rillwater crossing', coords: { x: 367, y: 1713 } },
  riverrun: { name: 'riverrun', coords: { x: 700, y: 1046 } },
  'rooks rest': { name: 'rooks rest', coords: { x: 1170, y: 899 } },
  rosby: { name: 'rosby', coords: { x: 1065, y: 803 } },
  runestone: { name: 'runestone', coords: { x: 1315, y: 1139 } },
  saltshore: { name: 'saltshore', coords: { x: 1076, y: 37 } },
  sandstone: { name: 'sandstone', coords: { x: 680, y: 123 } },
  sarsfield: { name: 'sarsfield', coords: { x: 431, y: 914 } },
  seagard: { name: 'seagard', coords: { x: 702, y: 1214 } },
  'sharp point': { name: 'sharp point', coords: { x: 1238, y: 792 } },
  silverhill: { name: 'silverhill', coords: { x: 589, y: 762 } },
  sisterton: { name: 'sisterton', coords: { x: 1018, y: 1454 } },
  skyreach: { name: 'skyreach', coords: { x: 702, y: 200 } },
  snakewood: { name: 'snakewood', coords: { x: 1197, y: 1298 } },
  'sows horn': { name: 'sows horn', coords: { x: 976, y: 855 } },
  spearhead: { name: 'spearhead', coords: { x: 964, y: 1278 } },
  starfall: { name: 'starfall', coords: { x: 552, y: 172 } },
  stokeworth: { name: 'stokeworth', coords: { x: 1022, y: 845 } },
  'stone hedge': { name: 'stone hedge', coords: { x: 819, y: 1032 } },
  stonedance: { name: 'stonedance', coords: { x: 1247, y: 749 } },
  strongsong: { name: 'strongsong', coords: { x: 1001, y: 1199 } },
  'sun house': { name: 'sun house', coords: { x: 409, y: 102 } },
  sunspear: { name: 'sunspear', coords: { x: 1253, y: 90 } },
  'the antlers': { name: 'the antlers', coords: { x: 980, y: 881 } },
  'the arbor': { name: 'the arbor', coords: { x: 248, y: 69 } },
  'the banefort': { name: 'the banefort', coords: { x: 432, y: 1080 } },
  'the crag': { name: 'the crag', coords: { x: 416, y: 1023 } },
  thedreadfort: { name: 'thedreadfort', coords: { x: 1059, y: 1911 } },
  'the eyrie': { name: 'the eyrie', coords: { x: 1050, y: 1089 } },
  'the redfort': { name: 'the redfort', coords: { x: 1142, y: 1026 } },
  'the tor': { name: 'the tor', coords: { x: 1054, y: 192 } },
  'the twins': { name: 'the twins', coords: { x: 728, y: 1293 } },
  'three towers': { name: 'three towers', coords: { x: 309, y: 198 } },
  'torrhens square': { name: 'torrhens square', coords: { x: 634, y: 1783 } },
  uplands: { name: 'uplands', coords: { x: 435, y: 269 } },
  vaith: { name: 'vaith', coords: { x: 1011, y: 78 } },
  wheatfield: { name: 'wheatfield', coords: { x: 847, y: 1232 } },
  'white harbor': { name: 'white harbor', coords: { x: 930, y: 1610 } },
  wickenden: { name: 'wickenden', coords: { x: 1158, y: 981 } },
  'widows watch': { name: 'widows watch', coords: { x: 1304, y: 1629 } },
  winterfell: { name: 'winterfell', coords: { x: 748, y: 1905 } },
  wyl: { name: 'wyl', coords: { x: 909, y: 343 } },
  yronwood: { name: 'yronwood', coords: { x: 878, y: 200 } },
};
